### ISSUE TITLE
OpenId4Vci crash during issueDocumentByOffer pre-authorized workflow

### ISSUE THREAD

**Issue by pietrini** [eu-digital-identity-wallet/eudi-lib-android-wallet-core#107]
System:
- SDK Version: 0.12.1
- Device: Emulator Android 25 with Google API images

Configuration:
``` kotlin
internal val config = EudiWalletConfig()
        .configureDocumentKeyCreation(
            userAuthenticationRequired = true,
            userAuthenticationTimeout = 1L,
            useStrongBoxForKeys = true
        )
        .configureOpenId4Vci {
            withIssuerUrl(issuerUrl)
            withClientId(clientId)
            withAuthFlowRedirectionURI(authFlowRedirectionURI)
        }
```
``` kotlin
        val issuerUrl = "https://dev.issuer.eudiw.dev"
        val clientId = "wallet-sdk-demo-android"
        val authFlowRedirectScheme = "eudi-openid4ci"
        val authFlowRedirectHost = "authorize"
        val credentialOfferScheme = "openid-credential-offer"
```

Issue:
- NPE when creation fo the document after calling
``` kotlin
event.resume(wallet.getDefaultCreateDocumentSettings())
```

How to reproduce:
- Start from a completely empty wallet.
- Scan or deeplink a pre-authorized offer.
- Input the verification code.

Log file:
[Medium-Phone-API-35-Android-15_2024-12-02_115903.log](https://github.com/user-attachments/files/17977639/Medium-Phone-API-35-Android-15_2024-12-02_115903.log)

**Comment by vkanellopoulos** [comment]
Hi @pietrini

Thank you for bringing this to our attention. We will investigate the issue and provide updates as soon as possible.

**Comment by pietrini** [comment]
Thanks a lot! Issue seems to be fixed
