### ISSUE TITLE
Support for SD-JWT-VC document format

### ISSUE THREAD

**Issue by AlexanderShenshin** [eu-digital-identity-wallet/eudi-lib-android-wallet-core#34]
First of all, thank you for your great work.

It's explicitly mentioned in README that SD-JWT-VC format is not yet supported for both Android and iOS EUDI wallet libraries, but it's also clear that you have this on a roadmap.

Do you have some approximate timeline for adding this support? Can we expect it to be added in the near future or for now you're focused on other features/improvements?

**Comment by AlexanderShenshin** [comment]
@vkanellopoulos ^
Sorry for pinging, just in case this was missed.

**Comment by Master3217** [comment]
Hello @stzouvaras  ,
Do you have any idea when will lib wallet core support document SD-JWT-VC format .
THANKS

**Comment by mgiakkou** [comment]
Dear Alexander,

The SD-JWT-VC is planned to be implemented in the coming quarters. You will soon receive further information regarding the implementation details and actual dates. Please stay tuned.

Thank you,
Michalis.

**Comment by mgiakkou** [comment]
Dear Alexander,

We have now published our Roadmap for the following quarters under: https://github.com/orgs/eu-digital-identity-wallet/projects/24. As you can see SD-JWT-VC is planned for Q4 of 2024 (https://github.com/eu-digital-identity-wallet/eudi-wallet-reference-implementation-roadmap/issues/3). Please follow the updates there.

Thank you,
Michalis.
