### ISSUE TITLE
Android Wallet Integration failure

### ISSUE THREAD

**Issue by dariocast** [eu-digital-identity-wallet/eudi-lib-android-wallet-core#57]
I cloned the project and built it up with docker compose, and after reading [the configuration specifications](https://github.com/eu-digital-identity-wallet/eudi-srv-pid-issuer?tab=readme-ov-file#configuration), I changed the urls using ngrok tool (to be able to test with a mobile wallet) in this way:
      - ISSUER_PUBLICURL=NGROK_EXPOSED_URL/pid-issuer
      - ISSUER_AUTHORIZATIONSERVER_PUBLICURL=NGROK_EXPOSED_URL/idp/realms/pid-issuer-realm
      - ISSUER_AUTHORIZATIONSERVER_METADATA=NGROK_EXPOSED_URL/idp/realms/pid-issuer-realm/.well-known/openid-configuration
      - ISSUER_AUTHORIZATIONSERVER_INTROSPECTION=NGROK_EXPOSED_URL/idp/realms/pid-issuer-realm/protocol/openid-connect/token/introspect

I was able to successfully load the frontend and retrieve a QR code for the issuance for each kind of format but the android demo wallet built from [the eudi repository](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui) is unable to resolve the credential offer.
The only error message I get is "If the issue persist, contact service".

**Comment by dariocast** [comment]
Hi, I tried the test suggested in this reply

> To verify your setup you can use a [simple](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt/blob/main/src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/WalletInitiatedIssuanceUsingAuthorizationFlow.kt) program that is included in the VCI lib. Just clone the repository, change credential [issuer](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt/blob/fe4bd6f761d2917aa19e28fb0e788db6656991c1/src/test/kotlin/eu/europa/ec/eudi/openid4vci/examples/Commons.kt#L44) to point to your set up, and run the program.

And I set the issuer to point to the local one provided by the [pid-issuer repository](https://github.com/eu-digital-identity-wallet/eudi-srv-pid-issuer):
    
`private const val BASE_URL = "https://localhost/pid-issuer"`

But when I run the test a content type appear to be not valid. In the specific the issuer pass a application/json while the test expect application/jwt. I attach a log of the execution with the error stack.

I do not understand if it is something related to this library or to be reported to the issuer. I am using the repositories as is, without any modification.


[error_log.pdf](https://github.com/user-attachments/files/15614156/error_log.pdf)

**Comment by babisRoutis** [comment]
Hi @dariocast 

I think you are very close, actually.

Can you please make sure that you use 
- in your docker compose [v0.2.2](https://github.com/eu-digital-identity-wallet/eudi-srv-pid-issuer/pkgs/container/eudi-srv-pid-issuer/223071401?tag=v0.2.2) ?
- you executing the program from the VCI main branch?

**Comment by dariocast** [comment]
Ok I updated to `v0.2.2` (default was `edge` and I haven't changed it).
Now the test is successful so I think the Core module works fine.
I will try to use the docker container locally with something like ngrok tool to expose the endpoints in order to check if the wallet works now.

**Comment by mgiakkou** [comment]
Dear Dario,

I guess this is resolved now, since no updates from your side, so I am proceeding and closing it. Please reopen it if requires.

Thank you,
Michalis.
