### ISSUE TITLE
SD JWT Support

### ISSUE THREAD

**Issue by Vaplet** [eu-digital-identity-wallet/eudi-lib-android-wallet-core#89]
Hello,
When we can expect support for SD JWT issuance / verification ? Is it better to start our own solution or wait, as we use the EUDI Wallet Core Lib ?

**Comment by mgiakkou** [comment]
Dear Vaplet,

Than kyou for your question. You can follow the roadmap of the Reference Implementation here: https://github.com/orgs/eu-digital-identity-wallet/projects/24/views/2. As you can see it is already in our roadmap and will be implmenter.

Thank you,
Michalis.
